apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-server.fullname" . }}
  labels: 
    {{- include "redis-server.labels" . | nindent 4 }}  
type: Opaque
data:
  redis_password: {{ .Values.redis.password | b64enc }}